execute pathogen#infect()

filetype on
syntax on

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

let mapleader = ","
let maplocalleader = "\\"

set number relativenumber

cnoremap w!! w !sudo tee %
inoremap jk <esc>

" Capitalize current word
inoremap <c-u> <esc>mzviwU`za

" Move current line up or down
nnoremap - mz:m +1<cr>`z
nnoremap _ mz:m -2<cr>`z

" Edit/source vimrc
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>sv :source $MYVIMRC<cr>

" Surround current word with quotes
nnoremap <leader>" mzviw<esc>a"<esc>bi"<esc>`zl
nnoremap <leader>' mzviw<esc>a'<esc>bi'<esc>`zl

" Surround visual selection with quotes
vnoremap <leader>" <esc>`<i"<esc>`>a"<esc>gv
vnoremap <leader>' <esc>`<i'<esc>`>a'<esc>gv

" Commenting
augroup commenting
  autocmd!
  autocmd FileType c,cpp,java nnoremap <buffer> <localleader>c mzI//<esc>`zll
  autocmd FileType python     nnoremap <buffer> <localleader>c mzI#<esc>`zl
  autocmd FileType c,cpp,java nnoremap <buffer> <localleader>C mz0i//<esc>`zll
  autocmd FileType python     nnoremap <buffer> <localleader>C mz0i#<esc>`zl
  autocmd FileType c,cpp,java vnoremap <buffer> <localleader>C <esc>:'<,'>s/^/\/\//<cr>gvll
  autocmd FileType python     vnoremap <buffer> <localleader>C <esc>:'<,'>s/^/#/<cr>gvll
augroup END

" Stuff from Learn Vimscript the Hard Way that I will probably delete
"onoremap in( :<c-u>normal! f(vi(<cr>
"onoremap il( :<c-u>normal! F(vi(<cr>
"onoremap an( :<c-u>normal! f(va(<cr>
"onoremap al( :<c-u>normal! F(va(<cr>
"onoremap in{ :<c-u>normal! f{vi{<cr>
"onoremap il{ :<c-u>normal! F{vi{<cr>
"onoremap an{ :<c-u>normal! f{va{<cr>
"onoremap al{ :<c-u>normal! F{va{<cr>

color xoria256-custom
